/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Persistencia.ArchivoTxt;
import Utilidades.Interfaz;
import javax.swing.JOptionPane;
import modelo.personas.*;
import static vista.paginaPrincipal.archivo;
import static vista.paginaPrincipal.detec;

/**
 *
 * @author steven
 */
public class Detectives extends javax.swing.JPanel {

    /**
     * Creates new form Detectives
     */
    public static Interfaz util;
    public static infoDetective info;
    public static ListaDetective modelo;
    public static Persona persona;
    public static ArchivoTxt txt1;

    public Detectives() {
        initComponents();
        //info = new infoDetective();
        util = new Interfaz();
        txt1 = new ArchivoTxt();
        modelo = new ListaDetective();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nombre2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        experiencia = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        nombre1 = new javax.swing.JTextField();
        apellido1 = new javax.swing.JTextField();
        capacitado = new javax.swing.JComboBox<>();

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(181, 220, 240));
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 60, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Informacion de detective");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen_2022-07-02_001027389.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        panelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 170, 10));

        nombre2.setBackground(new java.awt.Color(204, 204, 255));
        nombre2.setBorder(null);
        panelPrincipal.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 170, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ingrese segundo apellido:");
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Experiencia:");
        panelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Identificacion:");
        panelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("ingrese primer apellido:");
        panelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 40));
        panelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 280, 10));
        panelPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 270, 10));
        panelPrincipal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 180, 10));

        experiencia.setBackground(new java.awt.Color(204, 204, 255));
        experiencia.setBorder(null);
        panelPrincipal.add(experiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 280, 20));

        id.setBackground(new java.awt.Color(204, 204, 255));
        id.setBorder(null);
        panelPrincipal.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 260, 20));

        apellido2.setBackground(new java.awt.Color(204, 204, 255));
        apellido2.setBorder(null);
        panelPrincipal.add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 190, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("capacitado:");
        panelPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 30));

        jButton1.setBackground(new java.awt.Color(181, 220, 240));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("ingrese primer nombre:");
        panelPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("ingrese segundo nombre:");
        panelPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 40));
        panelPrincipal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 190, 10));
        panelPrincipal.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 190, 10));

        nombre1.setBackground(new java.awt.Color(204, 204, 255));
        nombre1.setBorder(null);
        panelPrincipal.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 190, 20));

        apellido1.setBackground(new java.awt.Color(204, 204, 255));
        apellido1.setBorder(null);
        panelPrincipal.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 190, 20));

        capacitado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione...", "Ciber Crimen", "Homicidio", "Narcotrafico" }));
        panelPrincipal.add(capacitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        util.showPanel(inicio.content, paginaPrincipal.detec);
        util.limpiarTabla(paginaPrincipal.detec.modelo_tabla);
        txt1.datosTextDetectives(paginaPrincipal.detec.modelo_tabla);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.experiencia.getText().equals("") || capacitado.getSelectedIndex()==0 || id.getText().equals("") || nombre1.getText().equals("") || nombre2.getText().equals("") || apellido1.getText().equals("") || apellido2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete todos los datos!");
        }else{
            leerNuevoDetective();
            registrarCaso();
            txt1.textDetectives(modelo);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void registrarCaso() {
        Persona nuevoDetective = this.leerNuevoDetective();
        this.modelo.insertarDetectives(nuevoDetective);
    }

    public Persona leerNuevoDetective() {

        byte experiencia = Byte.parseByte(this.experiencia.getText());
        String capacitado = String.valueOf(this.capacitado.getSelectedItem());
        String id =this.id.getText();
        String nombre1 = this.nombre1.getText();
        String nombre2 = this.nombre2.getText();
        String apellido1 = this.apellido1.getText();
        String apellido2 = this.apellido2.getText();
        persona = new Detective(experiencia, capacitado, id, nombre1, nombre2, apellido1,apellido2);

        return persona;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JComboBox<String> capacitado;
    public static javax.swing.JTextField experiencia;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    public static javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
