/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Utilidades.Interfaz;
import java.awt.event.KeyAdapter;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.personas.ListaDetective;
import modelo.personas.Persona;

/**
 *
 * @author steven
 */
public class infoSospechoso extends javax.swing.JPanel {

    /**
     * Creates new form infoSospechoso
     */
    public static Interfaz util;
    public static sospechosos sospe1;
    private ListaDetective modelo;
    DefaultTableModel modelo_tabla;
    TableRowSorter trs;
    private String titulosTabla[] = {"ID","NOMBRE 1","NOMBRE 2", "APELLIDO 1", "APPELIDO 2","ALIAS","EDAD","DIRECCION","CARACTERISTICAS"};
    
    
    public infoSospechoso() {
        initComponents();
        util = new Interfaz();
        sospe1 = new sospechosos();
        this.modelo = new ListaDetective();
        //leerPublicaciones();
        modelo_tabla = new DefaultTableModel();
        for (int i = 0; i < titulosTabla.length; i++) {
            modelo_tabla.addColumn(titulosTabla[i]);
        }
        this.tabla.setModel(modelo_tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        id = new javax.swing.JTextField();
        botonRegistar = new javax.swing.JToggleButton();
        botonEliminar = new javax.swing.JToggleButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(181, 220, 240));
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 60, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Informacion Sospechoso");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen_2022-07-02_001027389.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Digite la identificacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 198, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Primer nombre", "segundo nombre", "Primer apellido", "Segundo apellido", "Edad", "Alias", "Direccion", "Caracteristicas"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 346, 660, 120));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Id:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 174, 10));

        id.setBackground(new java.awt.Color(204, 204, 255));
        id.setBorder(null);
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 280, 180, 20));

        botonRegistar.setBackground(new java.awt.Color(181, 220, 240));
        botonRegistar.setText("REGISTRAR");
        botonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        botonEliminar.setBackground(new java.awt.Color(181, 220, 240));
        botonEliminar.setText("ELIMINAR");
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 698, 498));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        util.showPanel(inicio.content, Iniciar.menu);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistarActionPerformed
        util.showPanel(inicio.content, sospe1);
    }//GEN-LAST:event_botonRegistarActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }

        id.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + id.getText(), 0));
            }
        });
        trs = new TableRowSorter(modelo_tabla);
        tabla.setRowSorter(trs);  
    }//GEN-LAST:event_idKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonEliminar;
    private javax.swing.JToggleButton botonRegistar;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
