/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Persistencia.ArchivoTxt;
import Utilidades.Interfaz;
import java.util.List;
import modelo.personas.Persona;

/**
 *
 * @author steven
 */
public class paginaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form paginaPrincipal
     */
    public static Interfaz util;
    public static RegistrarCaso registrarCaso;
    public static MostrarCaso mCasos;
    public static infoDetective detec;
    public static infoSospechoso sospe;
    public static ArchivoTxt archivo;

    public paginaPrincipal() {
        initComponents();
        util = new Interfaz();
        archivo = new ArchivoTxt();
        registrarCaso = new RegistrarCaso();
        mCasos = new MostrarCaso();
        detec = new infoDetective();
        sospe = new infoSospechoso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        consultarDetectives = new javax.swing.JButton();
        registrarCasos = new javax.swing.JButton();
        consultarCasos = new javax.swing.JButton();
        consultarSospechosos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pagina Principal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen_2022-07-02_001027389.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("¿Que desea hacer?");

        consultarDetectives.setBackground(new java.awt.Color(181, 220, 240));
        consultarDetectives.setText("CONSULTAR DETECTIVES");
        consultarDetectives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarDetectivesActionPerformed(evt);
            }
        });

        registrarCasos.setBackground(new java.awt.Color(181, 220, 240));
        registrarCasos.setText("REGISTRAR CASOS");
        registrarCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCasosActionPerformed(evt);
            }
        });

        consultarCasos.setBackground(new java.awt.Color(181, 220, 240));
        consultarCasos.setText("CONSULTAR CASOS");
        consultarCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCasosActionPerformed(evt);
            }
        });

        consultarSospechosos.setBackground(new java.awt.Color(181, 220, 240));
        consultarSospechosos.setText("CONSULTAR SOSPECHOSOS");
        consultarSospechosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarSospechososActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consultarDetectives, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(registrarCasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consultarCasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultarSospechosos, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultarCasos, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(registrarCasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultarDetectives, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(consultarSospechosos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCasosActionPerformed
        util.showPanel(inicio.content, registrarCaso);
        
        List<Persona> lista = Detectives.modelo.leerDetectives();
            for (Persona c: lista) {
                this.registrarCaso.boxDetective.addItem(c.getNombre1());
                this.registrarCaso.boxSegundo.addItem(c.getNombre1());
            }
    }//GEN-LAST:event_registrarCasosActionPerformed

    private void consultarCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCasosActionPerformed
        util.showPanel(inicio.content, mCasos);
        util.limpiarTabla(mCasos.modelo_tabla);
        archivo.datosTextCasos(mCasos.modelo_tabla);

    }//GEN-LAST:event_consultarCasosActionPerformed

    private void consultarDetectivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarDetectivesActionPerformed
        util.showPanel(inicio.content, detec);
        util.limpiarTabla(detec.modelo_tabla);
        archivo.datosTextDetectives(detec.modelo_tabla);

    }//GEN-LAST:event_consultarDetectivesActionPerformed

    private void consultarSospechososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarSospechososActionPerformed
        util.showPanel(inicio.content, sospe);
        util.limpiarTabla(sospe.modelo_tabla);
        archivo.datosTextSospechosos(sospe.modelo_tabla);

    }//GEN-LAST:event_consultarSospechososActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarCasos;
    private javax.swing.JButton consultarDetectives;
    private javax.swing.JButton consultarSospechosos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton registrarCasos;
    // End of variables declaration//GEN-END:variables
}
